services:
  postgres:
    container_name: PostgreSQL
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=auctions
    restart: always
    ports:
      - 5400:5432
    volumes:
      - /var/lib/postgresql/data/
  mongo:
    container_name: MongoDB
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 5401:27017
    volumes:
      - /data/db