services:
  postgres:
    container_name: PostgreSQL
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=auctions
    restart: always
    ports:
      - 5400:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
  
volumes:
  pgdata: