apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-svc
spec:
  selector:
    matchLabels:
      app: bid-svc
  template:
    metadata:
      labels:
        app: bid-svc
    spec:
      containers:
        - name: bid-svc
          image: david/bid-svc
          imagePullPolicy: Never
          env:
            - name: ConnectionStrings__MongoDB
              valueFrom:
                secretKeyRef:
                  name: bid-secret
                  key: connectionString
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: username
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: password
            - name: JWT__Authority
              valueFrom:
                secretKeyRef:
                  name: bid-secret
                  key: authority
            - name: JWT__Issuer
              valueFrom:
                secretKeyRef:
                  name: bid-secret
                  key: issuer
            - name: JWT__ClientId
              valueFrom:
                secretKeyRef:
                  name: bid-secret
                  key: clientId
            - name: JWT__Audience
              valueFrom:
                secretKeyRef:
                  name: bid-secret
                  key: audience
          envFrom:
            - configMapRef:
                name: bid-svc-config
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: bid-svc
  ports:
    - port: 80
      targetPort: 80
