apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
spec:
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
        - name: gateway-svc
          image: david/gateway-svc
          imagePullPolicy: IfNotPresent
          env:
            - name: JWT__Authority
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: authority
            - name: JWT__Issuer
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: issuer
            - name: JWT__ClientId
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: clientId
            - name: JWT__Audience
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: audience
          envFrom:
            - configMapRef:
                name: gateway-svc-config
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
    - port: 80
      targetPort: 80
