apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-svc
spec:
  selector:
    matchLabels:
      app: notification-svc
  template:
    metadata:
      labels:
        app: notification-svc
    spec:
      containers:
        - name: notification-svc
          image: david/notification-svc
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: notification-svc-config
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: notification-clusterip
spec:
  type: ClusterIP
  selector:
    app: notification-svc
  ports:
    - port: 80
      targetPort: 80
