apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: postgresSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: auction-secret
type: Opaque
stringData:
  connectionString: Server=postgres-clusterip;User Id=postgres;Password=postgresSecretPw;Database=auctions
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  username: mongoUn
  password: mongoSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
stringData:
  username: rabbitUn
  password: rabbitSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: bid-secret
type: Opaque
stringData:
  connectionString: mongodb://mongoUn:mongoSecretPw@mongodb-clusterip
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
type: Opaque
stringData:
  connectionString: Server=postgres-clusterip;User Id=postgres;Password=postgresSecretPw;Database=identity
---
apiVersion: v1
kind: Secret
metadata:
  name: search-secret
type: Opaque
stringData:
  connectionString: mongodb://mongoUn:mongoSecretPw@mongodb-clusterip
---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
stringData:
  authSecret: thisisevenmoresecretthanprevioussecrets