apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  labels:
    app: dev
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/import/keycloak.json
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
spec:
  selector:
    matchLabels:
      app: dev
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: ""
  volumeMode: Filesystem
